export const CREATE_SOCIETY = "CREATE_SOCIETY";
export const CREATE_SOCIETY_INIT = "CREATE_SOCIETY_INIT";
export const CREATE_SOCIETY_SUCCESS = "CREATE_SOCIETY_SUCCESS";
export const CREATE_SOCIETY_FAILURE = "CREATE_SOCIETY_FAILURE";

export const GET_ALL_USER_EMAILS = "GET_ALL_USER_EMAILS";
export const GET_ALL_USER_EMAILS_INIT = "GET_ALL_USER_EMAILS_INIT";
export const GET_ALL_USER_EMAILS_SUCCESS = "GET_ALL_USER_EMAILS_SUCCESS";
export const GET_ALL_USER_EMAILS_FAILURE = "GET_ALL_USER_EMAILS_FAILURE";

// Action types for creating a family
export const CREATE_FAMILY = "CREATE_FAMILY";
export const CREATE_FAMILY_INIT = "CREATE_FAMILY_INIT";
export const CREATE_FAMILY_SUCCESS = "CREATE_FAMILY_SUCCESS";
export const CREATE_FAMILY_FAILURE = "CREATE_FAMILY_FAILURE";

// Action types for updating a family
export const UPDATE_FAMILY = "UPDATE_FAMILY";
export const UPDATE_FAMILY_INIT = "UPDATE_FAMILY_INIT";
export const UPDATE_FAMILY_SUCCESS = "UPDATE_FAMILY_SUCCESS";
export const UPDATE_FAMILY_FAILURE = "UPDATE_FAMILY_FAILURE";

// Action types for creating an activity
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const CREATE_ACTIVITY_INIT = "CREATE_ACTIVITY_INIT";
export const CREATE_ACTIVITY_SUCCESS = "CREATE_ACTIVITY_SUCCESS";
export const CREATE_ACTIVITY_FAILURE = "CREATE_ACTIVITY_FAILURE";

// Action types for updating an activity
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const UPDATE_ACTIVITY_INIT = "UPDATE_ACTIVITY_INIT";
export const UPDATE_ACTIVITY_SUCCESS = "UPDATE_ACTIVITY_SUCCESS";
export const UPDATE_ACTIVITY_FAILURE = "UPDATE_ACTIVITY_FAILURE";

// Action types for getting all families
export const GET_ALL_FAMILIES = "GET_ALL_FAMILIES";
export const GET_ALL_FAMILIES_INIT = "GET_ALL_FAMILIES_INIT";
export const GET_ALL_FAMILIES_SUCCESS = "GET_ALL_FAMILIES_SUCCESS";
export const GET_ALL_FAMILIES_FAILURE = "GET_ALL_FAMILIES_FAILURE";

// Action types for getting one family
export const GET_ONE_FAMILY = "GET_ONE_FAMILY";
export const GET_ONE_FAMILY_INIT = "GET_ONE_FAMILY_INIT";
export const GET_ONE_FAMILY_SUCCESS = "GET_ONE_FAMILY_SUCCESS";
export const GET_ONE_FAMILY_FAILURE = "GET_ONE_FAMILY_FAILURE";

// Action types for getting all activities
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
export const GET_ALL_ACTIVITIES_INIT = "GET_ALL_ACTIVITIES_INIT";
export const GET_ALL_ACTIVITIES_SUCCESS = "GET_ALL_ACTIVITIES_SUCCESS";
export const GET_ALL_ACTIVITIES_FAILURE = "GET_ALL_ACTIVITIES_FAILURE";

// Action types for getting one activity
export const GET_ONE_ACTIVITY = "GET_ONE_ACTIVITY";
export const GET_ONE_ACTIVITY_INIT = "GET_ONE_ACTIVITY_INIT";
export const GET_ONE_ACTIVITY_SUCCESS = "GET_ONE_ACTIVITY_SUCCESS";
export const GET_ONE_ACTIVITY_FAILURE = "GET_ONE_ACTIVITY_FAILURE";
