export const CREATE_SOCIETY = "CREATE_SOCIETY";
export const CREATE_SOCIETY_INIT = "CREATE_SOCIETY_INIT";
export const CREATE_SOCIETY_SUCCESS = "CREATE_SOCIETY_SUCCESS";
export const CREATE_SOCIETY_FAILURE = "CREATE_SOCIETY_FAILURE";
